GET https://api.redgifs.com/v2/auth/temporary
###
GET https://api.redgifs.com/v2/gifs/search?type=g&order=latest&count=10&page=2&tags=Strap+On|Gay|Twink
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJpYXQiOjE3NjIwOTgyOTQsImF1ZCI6Imh0dHBzOi8vYXBpLnJlZGdpZnMuY29tIiwiYXpwIjoiMTgyM2MzMWY3ZDMtNzQ1YS02NTg5LTAwMDUtZDhlOGZlMGE0NGMyIiwiZXhwIjoxNzYyMTg0Njk0LCJzdWIiOiJjbGllbnQvMTgyM2MzMWY3ZDMtNzQ1YS02NTg5LTAwMDUtZDhlOGZlMGE0NGMyIiwic2NvcGVzIjoicmVhZCIsInZhbGlkX2FkZHIiOiI4Mi40NS4zMi4xNzYiLCJ2YWxpZF9hZ2VudCI6InZzY29kZS1yZXN0Y2xpZW50IiwicmF0ZSI6LTEsImh0dHBzOi8vcmVkZ2lmcy5jb20vc2Vzc2lvbi1pZCI6IjM0MDI0MDU4MjkzMDczMzU0NSJ9.kDE310hOmt0GhsU9QTy2RrWHDMEjSRse59ShRV4_HV2B_nS7Z903npiNAkr8gX4t72V9uqLxCyiRgx1iy7DfDHt6Xv-IoVVPbJrlVvuDcswpW5xVZBoP2XI5PHJyGZWeCWSefmfSroNY_WATyH_FnnHVTkcY7T1lOJD2shNS6xiDwMHaVfHqudzEqyZYgY23h86Iro77KMuiQ7tQQT9OoJ4__2Jjo2FYBAz3zxxIcq1NG0yhGSRHeiMv99ac5r19dl0wYmXpBEPBD-NBJh3C0qkzj7dm3yJT5fMzHlckuo42fm9O_AJ-6kLAVHR49SSZHM3jld_pYcBLCAjpV7lI4w
###
GET https://media.redgifs.com/RepentantLoudTattler-mobile.mp4

###
GET https://api.rule34.xxx/index.php?page=dapi&s=post&q=index&api_key=cd9019fd0570835bc9d8ddc8eef60d5adb38e9a0d7a4eb1600dc697c4f14b1644fa8cebe65b0d7834d2ffdfe8bc49d9b5137aa947975773f1af456437c5373a2&user_id=5336324&json=1&tags=big_tits+animated+futanari+standing_dp

###
GET https://api.rule34.xxx/index.php?page=dapi&s=tag&q=index&api_key=cd9019fd0570835bc9d8ddc8eef60d5adb38e9a0d7a4eb1600dc697c4f14b1644fa8cebe65b0d7834d2ffdfe8bc49d9b5137aa947975773f1af456437c5373a2&user_id=5336324