GET https://api.redgifs.com/v2/auth/temporary
###
GET https://api.redgifs.com/v2/gifs/search?type=g&order=latest&count=10&page=2&tags=Strap+On|Gay|Twink
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJpYXQiOjE3NjU3MTkyMTMsImF1ZCI6Imh0dHBzOi8vYXBpLnJlZGdpZnMuY29tIiwiYXpwIjoiMTgyM2MzMWY3ZDMtNzQ1YS02NTg5LTAwMDUtZDhlOGZlMGE0NGMyIiwiZXhwIjoxNzY1ODA1NjEzLCJzdWIiOiJjbGllbnQvMTgyM2MzMWY3ZDMtNzQ1YS02NTg5LTAwMDUtZDhlOGZlMGE0NGMyIiwic2NvcGVzIjoicmVhZCIsInZhbGlkX2FkZHIiOiI4Mi40NS4zMi4xNzYiLCJ2YWxpZF9hZ2VudCI6InZzY29kZS1yZXN0Y2xpZW50IiwicmF0ZSI6LTEsImh0dHBzOi8vcmVkZ2lmcy5jb20vc2Vzc2lvbi1pZCI6IjM1NjUyNzc5NDkwMzE5MjQwNCJ9.tiNDq8uDXapS5Ie-SY_Bkpszp8C_7Ru3ZoH_riF3iL_S__dZ7dkOyIwfRd-pJAqrx3H_GrIFO-91Df3XNETn5E2TLwufS0c86HYM33B3HHeKx9U_-dkHjLyK3mKgFPE4YSrg8xVFjbE7gWL1q_rk_R8G_29G80ELJHG78EHpWn2LJ_hQdwNq75aSo_dR0Ph2zoV3vcQjhLaCQe_VQ0NnZ5daLmd5dA4lFdWwyWVUHhHpmveSUpLcpCKkHoMcJqqbtOIxifDfSWFtVLaxIrBK4DZV_EW80F1D7TPSYnSs4AwbLd6TzlKkytZz3s32dqz4781qd1Zm7jXObqQll7xySg

###

GET https://api.redgifs.com/v1/users/anneaof21
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJpYXQiOjE3NjU3MTkyMTMsImF1ZCI6Imh0dHBzOi8vYXBpLnJlZGdpZnMuY29tIiwiYXpwIjoiMTgyM2MzMWY3ZDMtNzQ1YS02NTg5LTAwMDUtZDhlOGZlMGE0NGMyIiwiZXhwIjoxNzY1ODA1NjEzLCJzdWIiOiJjbGllbnQvMTgyM2MzMWY3ZDMtNzQ1YS02NTg5LTAwMDUtZDhlOGZlMGE0NGMyIiwic2NvcGVzIjoicmVhZCIsInZhbGlkX2FkZHIiOiI4Mi40NS4zMi4xNzYiLCJ2YWxpZF9hZ2VudCI6InZzY29kZS1yZXN0Y2xpZW50IiwicmF0ZSI6LTEsImh0dHBzOi8vcmVkZ2lmcy5jb20vc2Vzc2lvbi1pZCI6IjM1NjUyNzc5NDkwMzE5MjQwNCJ9.tiNDq8uDXapS5Ie-SY_Bkpszp8C_7Ru3ZoH_riF3iL_S__dZ7dkOyIwfRd-pJAqrx3H_GrIFO-91Df3XNETn5E2TLwufS0c86HYM33B3HHeKx9U_-dkHjLyK3mKgFPE4YSrg8xVFjbE7gWL1q_rk_R8G_29G80ELJHG78EHpWn2LJ_hQdwNq75aSo_dR0Ph2zoV3vcQjhLaCQe_VQ0NnZ5daLmd5dA4lFdWwyWVUHhHpmveSUpLcpCKkHoMcJqqbtOIxifDfSWFtVLaxIrBK4DZV_EW80F1D7TPSYnSs4AwbLd6TzlKkytZz3s32dqz4781qd1Zm7jXObqQll7xySg

###
GET https://api.redgifs.com/v2/users/bbc21344/search?type=g&order=new&count=10
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJpYXQiOjE3NjIyMDg4NDAsImF1ZCI6Imh0dHBzOi8vYXBpLnJlZGdpZnMuY29tIiwiYXpwIjoiMTgyM2MzMWY3ZDMtNzQ1YS02NTg5LTAwMDUtZDhlOGZlMGE0NGMyIiwiZXhwIjoxNzYyMjk1MjQwLCJzdWIiOiJjbGllbnQvMTgyM2MzMWY3ZDMtNzQ1YS02NTg5LTAwMDUtZDhlOGZlMGE0NGMyIiwic2NvcGVzIjoicmVhZCIsInZhbGlkX2FkZHIiOiIxNTkuMjYuMTE2LjMwIiwidmFsaWRfYWdlbnQiOiJ2c2NvZGUtcmVzdGNsaWVudCIsInJhdGUiOi0xLCJodHRwczovL3JlZGdpZnMuY29tL3Nlc3Npb24taWQiOiIzNDA1MjA2NTgwNTAwOTU3ODAifQ.uVK2Vhz0Qc8BF9QgYlG9MrHdw31wgzNDM4OGsZ1ZgZIqX2frTgVPfVrvQuubEwkIcx2tYraV11P6GrlEvfYeV-K5Yn-RA5uBut0pd9Lf8c-VIY1xrRzVvBOw9Hrlc87B0ioxPOxfES9A_LO9CXtTrJhcsmx-xqMZDMRLqAUugOJi-1WgC4zmMfdjZI-QvXFcE5LDeGDPauZ7C1KXiuL_GnyxPjpmFW9RPp5aKfSivkMS2_wz8uz_stoHr4W-4Oebt8H9siiybqw8mzFQKQTWNMKSXSm73B2KwRMbOLQhxCQ1vQg-npixtE5i3tNnMi2zSwjYYvOaEXCG80LyJmoIiA
###
GET https://media.redgifs.com/RepentantLoudTattler-mobile.mp4

###
GET https://api.rule34.xxx/index.php?page=dapi&s=post&q=index&api_key=cd9019fd0570835bc9d8ddc8eef60d5adb38e9a0d7a4eb1600dc697c4f14b1644fa8cebe65b0d7834d2ffdfe8bc49d9b5137aa947975773f1af456437c5373a2&user_id=5336324&json=1&tags=big_tits+animated+futanari+standing_dp

###
GET https://api.rule34.xxx/index.php?page=dapi&s=tag&q=index&api_key=cd9019fd0570835bc9d8ddc8eef60d5adb38e9a0d7a4eb1600dc697c4f14b1644fa8cebe65b0d7834d2ffdfe8bc49d9b5137aa947975773f1af456437c5373a2&user_id=5336324


#### https://github.com/scrazzz/redgifs/tree/main/redgifs
### https://redgifs.readthedocs.io/en/stable/api.html#redgifs.API.search